### ISSUE TITLE
GPUDB object instantiation with python 3.9.6 raises attribute error

### ISSUE THREAD

**Issue by TerryLines** [kineticadb/kinetica-api-python#12]
Running this:

  ```
db = gpudb.GPUdb(
      encoding='BINARY',
      host=KINETICA_HOST[0],
      primary_host=KINETICA_HOST[0],
      username=KINETICA_USER ,
      password=KINETICA_PASS,
      disable_failover=True,
      disable_auto_discovery=True,
      skip_ssl_cert_verification=True
  )
```

gives this error
```
.underwrite/lib/python3.9/site-packages/gpudb/gpudb.py:4711: in __init__
    self.__construct( host, options, *args, **kwargs )
.underwrite/lib/python3.9/site-packages/gpudb/gpudb.py:4804: in __construct
    self.auth = base64.encodestring( self.auth ).decode( "ascii" ).replace('\n', '')
E   AttributeError: module 'base64' has no attribute 'encodestring'
```

using gpudb 7.1.5 and python 3.9.6. Works fine with python 3.7.11

**Comment by kylesutton** [comment]
@TerryLines - I believe this is fixed in the latest release of the API (7.1.8.3).  Can you give that a try?

Thanks,
Kyle
